#!/bin/csh -f
# Bodgy script to make fonts... Use the fonts I commit, probably easier
cd /tmp/5x9
/projects/tools/bin/5x9 --style=JTD
foreach d (0.96 1.92 2.88 3.84)
	inkscape --export-area=0:100:499:999 -echar.png -d$d u0020.svg
	setenv W `identify -format '%W' char.png`
	setenv H `identify -format '%H' char.png`
	set f="font$W.h"
	identify -format "const uint8_t font$W[][$H][$W]={" char.png > $f
	echo "" >> $f
	foreach u (u00[0-7]*.svg)
		inkscape --export-area=0:100:499:999 -echar.png -d$d "$u"
		convert char.png -flatten char.gray
		echo "{ // $u:r" >> $f
		od -v -tx1 -w$W -Anone char.gray | sed -e 's/\([0-9a-x][0-9a-x]\)/0x\1,/g' -e 's/^/{/' -e 's/,$/},/' >> $f
		echo "}," >> $f
	end
	echo "};" >> $f
end
