#!/bin/csh -f
# Bodgy script to make fonts... Use the fonts I commit, probably easier
if(! -e /tmp/5x9) then
	/projects/tools/bin/5x9 --style=JTD
	cd /tmp/5x9
	foreach u (u00[0-7]*.svg)
		echo $u
		inkscape -f $u --verb EditSelectAll --verb SelectionUnGroup --verb SelectionUnion --verb FileSave --verb FileQuit
		inkscape -z --export-area=0:102:600:1024 -e$u:r.png $u >& /dev/null
	end
endif
cd /tmp/5x9
foreach n (1 2 3 4 5)
	echo "font$n"
	@ W = $n * 6
	@ H = $n * 9
	@ b = $W * $H / 2
	set f="font$n.h"
	echo "const uint8_t font${n}[]={ // $W/$H ($b bytes per character)" > $f
	foreach u (u00[0-7]*.svg)
		convert $u:r.png -flatten -negate -scale ${W}x${H}'!' char.gray
		echo "// $u:r" >> $f
		od -v -tx1 -w$W -Anone char.gray | sed -e 's/\([0-9a-f]\)[0-9a-f] \([0-9a-f]\)[0-9a-f]/0x\1\2,/g' >> $f
	end
	echo "};" >> $f
end
